import styles from './Sitemap.module.scss'
import classNames from 'classnames/bind';

const cx = classNames.bind(styles)

function Sitemap() {
    return (
        <div className={cx('sitemap')}>
            <div id="content">
                <h1>XML Sitemap</h1>

                Generated by
                <a href="https://yoa.st/1y5">Yoast SEO</a>
                , this is an XML Sitemap, meant for consumption by search engines.
                <br></br>
                You can find more information about XML sitemaps on
                <a href="https://sitemaps.org">sitemaps.org</a>.
                <p>
                    This XML Sitemap Index file contains 3 sitemaps.
                </p>
                <table id="sitemap" ><thead><tr><th width="75%">Sitemap</th><th width="25%">Last Modified</th></tr></thead><tbody><tr><td><a href="https://shop.mixigaming.com/post-sitemap.xml">https://shop.mixigaming.com/post-sitemap.xml</a></td><td>  </td></tr><tr><td><a href="https://shop.mixigaming.com/page-sitemap.xml">https://shop.mixigaming.com/page-sitemap.xml</a></td><td>2022-07-30 09:21 +00:00</td></tr><tr><td><a href="https://shop.mixigaming.com/product-sitemap.xml">https://shop.mixigaming.com/product-sitemap.xml</a></td><td>2022-08-24 13:18 +00:00</td></tr></tbody></table></div>

        </div>
    );
}

export default Sitemap;